# My beliefs
Review every quarter ([README](README.md)).

## On the purpose of life
- There is probably no purpose and meaning in life.
- That does not mean I cannot make one up myself.

## On navigating through my life as a journey
- Thinking in themes makes it easier to have a set of consistent values.
- Having a set of consistent values makes it easier to make important decisions.
- Having an easier time making important decisions improves quality of life.
- Being flexible and avoiding useless dogma is important. Being principled and avoiding unconvincing flip-flopping is also important.
- These two values together represent a dilemma when living my life.
- So far, my only answer to this dilemma is to :
   - choose my themes very carefully,
   - embrace these themes as mine completely,
   - stick to my themes religiously,
   - allow extreme flexibility in my choice of tactics and strategies to accomplish my themes,
   - while allowing minimal flexibility in my choice of themes after I have chosen them.
   
## Themes
- I adopt two themes to live by: Be generous. Be consistent.
- My opinion and choices in all or most issues like morality, interpersonal relationships, and even business-related stuff will be determined by these two themes.

## On making sense of the world around us
- Frankly, I have no idea and no certainty what is true for sure and what is false for sure.
- At this stage, I trust the scientists with regards to physical phenomena while not dismissing the mystics and the philosophers.

## On Usefulness vs Accuracy
- Usefulness is more important than accuracy.
- I can use the wrong working or model, but still arrive at the correct or useful answer. In my life, having the correct or useful answer is usually more important.
- Knowing exactly why something works is usually less important than knowing what works.
- Facts, strategies, tactics, problems, and solutions do not exist in a vaccuum. They exist within a context, a narrative, or a perspective.
- From this point onwards, the word `perspective` is used interchangeably with `context` and `narrative`.

## On Truth
- The most important `truths` are often deep and powerful. They are applicable in many areas and across multiple contexts.
- For these truths to be applicable in so many areas and contexts, they need to be fluid.
- By its nature, language will always fix and define concepts.
- We communicate with one another using language. 
- This means that the most important and fluid `truths` likely cannot be taught, or explained. Hence the term `ineffable`. These important `truths` can only be shown or experienced. They cannot be explained fully. They can be hinted at, or explained indirectly.
- There is a non-zero chance that some `truths` cannot even be known at all.

## On Judgement
- Everything is important. Some things are **more** important than others.
- A good perspective is worth 80 IQ points.
- Choosing a useful perspective often opens up strategies and solutions not previously thought of before. 
- Choosing a useful perspective can also have the effect of rendering a problem into nothing, or turning a disadvantage into a benefit.

## Meta   
- We have some control over what we believe in, but not as much as we tend to think we have.
- Some of my beliefs will be proven wrong, and that's okay.
- I'm willing to be convinced that my beliefs are wrong.
- Making and maintaining this list is useful and fun (you should do it too)